services:
  # Backend Django API
  - type: web
    name: medicore-backend
    env: python
    plan: free
    buildCommand: cd backend && bash build.sh
    startCommand: cd backend && gunicorn Medicore.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: 0
      - key: ALLOWED_HOSTS
        value: medicore-e9xf.onrender.com
      - key: CORS_ALLOW_ALL_ORIGINS
        value: 0
      - key: CORS_ALLOWED_ORIGINS
        value: https://medi-core-ho5qpfz6i-jared-ahazas-projects.vercel.app
      - key: CORS_ALLOWED_ORIGIN_REGEXES
        value: ^https://.*\.vercel\.app$
      - key: DB_NAME
        fromDatabase:
          name: medicore-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: medicore-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: medicore-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: medicore-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: medicore-db
          property: port

  # PostgreSQL Database
  - type: pserv
    name: medicore-db
    env: postgresql
    plan: free



